"""AWS SigV4 test vectors — GENERATED by tools/gen_sigv4_vectors.py.

Source: the published `aws-sig-v4-test-suite`, as vendored in
awslabs/aws-c-auth (`tests/aws-signing-test-suite/v4`). Each case gives the
signer's inputs and the expected canonical request, string to sign and
signature. `get-header-value-multiline` is omitted: obs-fold header values
were removed from HTTP/1.1 by RFC 7230 and cannot be expressed as a
Name/Value pair.
"""

from objectstore.http import Header
from objectstore.sigv4 import QueryParam


@fieldwise_init
struct SigV4Case(Copyable, Movable):
    var name: String
    var method: String
    var path: String
    var params: List[QueryParam]
    var headers: List[Header]
    var payload_hash: String
    var access_key: String
    var secret_key: String
    var region: String
    var service: String
    var amz_date: String
    var normalize: Bool
    var canonical: String
    var sts: String
    var signature: String


def sigv4_cases() -> List[SigV4Case]:
    var out = List[SigV4Case]()

    var params_get_header_key_duplicate = List[QueryParam]()
    var headers_get_header_key_duplicate = List[Header]()
    headers_get_header_key_duplicate.append(Header("Host", "example.amazonaws.com"))
    headers_get_header_key_duplicate.append(Header("My-Header1", "value2"))
    headers_get_header_key_duplicate.append(Header("My-Header1", "value2"))
    headers_get_header_key_duplicate.append(Header("My-Header1", "value1"))
    headers_get_header_key_duplicate.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-header-key-duplicate", "GET", "/", params_get_header_key_duplicate^, headers_get_header_key_duplicate^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nmy-header1:value2,value2,value1\nx-amz-date:20150830T123600Z\n\nhost;my-header1;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\ndc7f04a3abfde8d472b0ab1a418b741b7c67174dad1551b4117b15527fbe966c", "c9d5ea9f3f72853aea855b47ea873832890dbdd183b4468f858259531a5138ea"))

    var params_get_header_value_order = List[QueryParam]()
    var headers_get_header_value_order = List[Header]()
    headers_get_header_value_order.append(Header("Host", "example.amazonaws.com"))
    headers_get_header_value_order.append(Header("My-Header1", "value4"))
    headers_get_header_value_order.append(Header("My-Header1", "value1"))
    headers_get_header_value_order.append(Header("My-Header1", "value3"))
    headers_get_header_value_order.append(Header("My-Header1", "value2"))
    headers_get_header_value_order.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-header-value-order", "GET", "/", params_get_header_value_order^, headers_get_header_value_order^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nmy-header1:value4,value1,value3,value2\nx-amz-date:20150830T123600Z\n\nhost;my-header1;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n31ce73cd3f3d9f66977ad3dd957dc47af14df92fcd8509f59b349e9137c58b86", "08c7e5a9acfcfeb3ab6b2185e75ce8b1deb5e634ec47601a50643f830c755c01"))

    var params_get_header_value_trim = List[QueryParam]()
    var headers_get_header_value_trim = List[Header]()
    headers_get_header_value_trim.append(Header("Host", "example.amazonaws.com"))
    headers_get_header_value_trim.append(Header("My-Header1", " value1"))
    headers_get_header_value_trim.append(Header("My-Header2", " \"a   b   c\""))
    headers_get_header_value_trim.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-header-value-trim", "GET", "/", params_get_header_value_trim^, headers_get_header_value_trim^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nmy-header1:value1\nmy-header2:\"a b c\"\nx-amz-date:20150830T123600Z\n\nhost;my-header1;my-header2;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\na726db9b0df21c14f559d0a978e563112acb1b9e05476f0a6a1c7d68f28605c7", "acc3ed3afb60bb290fc8d2dd0098b9911fcaa05412b367055dee359757a9c736"))

    var params_get_relative_normalized = List[QueryParam]()
    var headers_get_relative_normalized = List[Header]()
    headers_get_relative_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_relative_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-relative-normalized", "GET", "/example/..", params_get_relative_normalized^, headers_get_relative_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_relative_relative_normalized = List[QueryParam]()
    var headers_get_relative_relative_normalized = List[Header]()
    headers_get_relative_relative_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_relative_relative_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-relative-relative-normalized", "GET", "/example1/example2/../..", params_get_relative_relative_normalized^, headers_get_relative_relative_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_relative_relative_unnormalized = List[QueryParam]()
    var headers_get_relative_relative_unnormalized = List[Header]()
    headers_get_relative_relative_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_relative_relative_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-relative-relative-unnormalized", "GET", "/example1/example2/../..", params_get_relative_relative_unnormalized^, headers_get_relative_relative_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n/example1/example2/../..\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n76115030c0f3ff06c20fdff5ceb6d5e0b835a1743e00b94fea7c7f381269437b", "dc33e0856fd4baca4d7aa2146c38958283844764f38c74252a333df5e613003b"))

    var params_get_relative_unnormalized = List[QueryParam]()
    var headers_get_relative_unnormalized = List[Header]()
    headers_get_relative_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_relative_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-relative-unnormalized", "GET", "/example/..", params_get_relative_unnormalized^, headers_get_relative_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n/example/..\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n0511f456aa502b456d135fcb9d749374a55228f9dbeedda1eacf659e05b0615b", "eca7ead57bb5aa5c8e28007acd4ff04e1ff9a0ff3b237ec1554a184887ff9282"))

    var params_get_slash_dot_slash_normalized = List[QueryParam]()
    var headers_get_slash_dot_slash_normalized = List[Header]()
    headers_get_slash_dot_slash_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_dot_slash_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-dot-slash-normalized", "GET", "/./", params_get_slash_dot_slash_normalized^, headers_get_slash_dot_slash_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_slash_dot_slash_unnormalized = List[QueryParam]()
    var headers_get_slash_dot_slash_unnormalized = List[Header]()
    headers_get_slash_dot_slash_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_dot_slash_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-dot-slash-unnormalized", "GET", "/./", params_get_slash_dot_slash_unnormalized^, headers_get_slash_dot_slash_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n/./\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nd67825e2268bd77a97c7688b8d72c31a3c1855b309808505ba0a9747d2465aa7", "68714168e6557f8f2de0ef956fc24dc2593a4bd2961f8df51898d8a134695145"))

    var params_get_slash_normalized = List[QueryParam]()
    var headers_get_slash_normalized = List[Header]()
    headers_get_slash_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-normalized", "GET", "//", params_get_slash_normalized^, headers_get_slash_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_slash_pointless_dot_normalized = List[QueryParam]()
    var headers_get_slash_pointless_dot_normalized = List[Header]()
    headers_get_slash_pointless_dot_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_pointless_dot_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-pointless-dot-normalized", "GET", "/./example", params_get_slash_pointless_dot_normalized^, headers_get_slash_pointless_dot_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/example\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n214d50c111a8edc4819da6a636336472c916b5240f51e9a51b5c3305180cf702", "ef75d96142cf21edca26f06005da7988e4f8dc83a165a80865db7089db637ec5"))

    var params_get_slash_pointless_dot_unnormalized = List[QueryParam]()
    var headers_get_slash_pointless_dot_unnormalized = List[Header]()
    headers_get_slash_pointless_dot_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_pointless_dot_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-pointless-dot-unnormalized", "GET", "/./example", params_get_slash_pointless_dot_unnormalized^, headers_get_slash_pointless_dot_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n/./example\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n73895e0e829507e28e39fd24669aedc2434a8e179e547e3c075b42921f952cdb", "beb03f223f7deae4146464f06e29eebbee9c8afbe15c290cf07aa8b119e14cff"))

    var params_get_slash_unnormalized = List[QueryParam]()
    var headers_get_slash_unnormalized = List[Header]()
    headers_get_slash_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slash_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slash-unnormalized", "GET", "//", params_get_slash_unnormalized^, headers_get_slash_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n//\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n80cb39203d058af815de2b79250ff56e1b73eb9b4718c86556cdc6f150c5d209", "c88bcd3d312d75078c0cd961d6deae3f4c754924b01669efcfcb439fd5e5b76e"))

    var params_get_slashes_normalized = List[QueryParam]()
    var headers_get_slashes_normalized = List[Header]()
    headers_get_slashes_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slashes_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slashes-normalized", "GET", "//example//", params_get_slashes_normalized^, headers_get_slashes_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/example/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\ncb96b4ac96d501f7c5c15bc6d67b3035061cfced4af6585ad927f7e6c985c015", "9a624bd73a37c9a373b5312afbebe7a714a789de108f0bdfe846570885f57e84"))

    var params_get_slashes_unnormalized = List[QueryParam]()
    var headers_get_slashes_unnormalized = List[Header]()
    headers_get_slashes_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_slashes_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-slashes-unnormalized", "GET", "//example//", params_get_slashes_unnormalized^, headers_get_slashes_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n//example//\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n528ec3105ee1f34ab014bb0a1a45da0ed2742a4fea3555149e5b4d5d201eb240", "87cca117541a147f6df867677d98a7d80dff226d2bfca9e4ffa899665623c7e5"))

    var params_get_space_normalized = List[QueryParam]()
    var headers_get_space_normalized = List[Header]()
    headers_get_space_normalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_space_normalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-space-normalized", "GET", "/example space/", params_get_space_normalized^, headers_get_space_normalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/example%20space/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n63ee75631ed7234ae61b5f736dfc7754cdccfedbff4b5128a915706ee9390d86", "652487583200325589f1fba4c7e578f72c47cb61beeca81406b39ddec1366741"))

    var params_get_space_unnormalized = List[QueryParam]()
    var headers_get_space_unnormalized = List[Header]()
    headers_get_space_unnormalized.append(Header("Host", "example.amazonaws.com"))
    headers_get_space_unnormalized.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-space-unnormalized", "GET", "/example space/", params_get_space_unnormalized^, headers_get_space_unnormalized^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", False, "GET\n/example%20space/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n63ee75631ed7234ae61b5f736dfc7754cdccfedbff4b5128a915706ee9390d86", "652487583200325589f1fba4c7e578f72c47cb61beeca81406b39ddec1366741"))

    var params_get_unreserved = List[QueryParam]()
    var headers_get_unreserved = List[Header]()
    headers_get_unreserved.append(Header("Host", "example.amazonaws.com"))
    headers_get_unreserved.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-unreserved", "GET", "/-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", params_get_unreserved^, headers_get_unreserved^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n6a968768eefaa713e2a6b16b589a8ea192661f098f37349f4e2c0082757446f9", "07ef7494c76fa4850883e2b006601f940f8a34d404d0cfa977f52a65bbf5f24f"))

    var params_get_utf8 = List[QueryParam]()
    var headers_get_utf8 = List[Header]()
    headers_get_utf8.append(Header("Host", "example.amazonaws.com"))
    headers_get_utf8.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-utf8", "GET", "/ሴ", params_get_utf8^, headers_get_utf8^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/%E1%88%B4\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n2a0a97d02205e45ce2e994789806b19270cfbbb0921b278ccf58f5249ac42102", "8318018e0b0f223aa2bbf98705b62bb787dc9c0e678f255a891fd03141be5d85"))

    var params_get_vanilla = List[QueryParam]()
    var headers_get_vanilla = List[Header]()
    headers_get_vanilla.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla", "GET", "/", params_get_vanilla^, headers_get_vanilla^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_vanilla_empty_query_key = List[QueryParam]()
    params_get_vanilla_empty_query_key.append(QueryParam("Param1", "value1"))
    var headers_get_vanilla_empty_query_key = List[Header]()
    headers_get_vanilla_empty_query_key.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_empty_query_key.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-empty-query-key", "GET", "/", params_get_vanilla_empty_query_key^, headers_get_vanilla_empty_query_key^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\nParam1=value1\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n1e24db194ed7d0eec2de28d7369675a243488e08526e8c1c73571282f7c517ab", "a67d582fa61cc504c4bae71f336f98b97f1ea3c7a6bfe1b6e45aec72011b9aeb"))

    var params_get_vanilla_query = List[QueryParam]()
    var headers_get_vanilla_query = List[Header]()
    headers_get_vanilla_query.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_query.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-query", "GET", "/", params_get_vanilla_query^, headers_get_vanilla_query^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nbb579772317eb040ac9ed261061d46c1f17a8133879d6129b6e1c25292927e63", "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31"))

    var params_get_vanilla_query_order_encoded = List[QueryParam]()
    params_get_vanilla_query_order_encoded.append(QueryParam("Param-3", "Value3"))
    params_get_vanilla_query_order_encoded.append(QueryParam("Param", "Value2"))
    params_get_vanilla_query_order_encoded.append(QueryParam("ሴ", "Value1"))
    var headers_get_vanilla_query_order_encoded = List[Header]()
    headers_get_vanilla_query_order_encoded.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_query_order_encoded.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-query-order-encoded", "GET", "/", params_get_vanilla_query_order_encoded^, headers_get_vanilla_query_order_encoded^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n%E1%88%B4=Value1&Param=Value2&Param-3=Value3\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n868294f5c38bd141c4972a373a76654f1418a8e4fc18b2e7903ae45e8ae0ec71", "371d3713e185cc334048618a97f809c9ffe339c62934c032af5a0e595648fcac"))

    var params_get_vanilla_query_order_key_case = List[QueryParam]()
    params_get_vanilla_query_order_key_case.append(QueryParam("Param2", "value2"))
    params_get_vanilla_query_order_key_case.append(QueryParam("Param1", "value1"))
    var headers_get_vanilla_query_order_key_case = List[Header]()
    headers_get_vanilla_query_order_key_case.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_query_order_key_case.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-query-order-key-case", "GET", "/", params_get_vanilla_query_order_key_case^, headers_get_vanilla_query_order_key_case^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\nParam1=value1&Param2=value2\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n816cd5b414d056048ba4f7c5386d6e0533120fb1fcfa93762cf0fc39e2cf19e0", "b97d918cfa904a5beff61c982a1b6f458b799221646efd99d3219ec94cdf2500"))

    var params_get_vanilla_query_unreserved = List[QueryParam]()
    params_get_vanilla_query_unreserved.append(QueryParam("-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", "-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"))
    var headers_get_vanilla_query_unreserved = List[Header]()
    headers_get_vanilla_query_unreserved.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_query_unreserved.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-query-unreserved", "GET", "/", params_get_vanilla_query_unreserved^, headers_get_vanilla_query_unreserved^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz=-._~0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nc30d4703d9f799439be92736156d47ccfb2d879ddf56f5befa6d1d6aab979177", "9c3e54bfcdf0b19771a7f523ee5669cdf59bc7cc0884027167c21bb143a40197"))

    var params_get_vanilla_utf8_query = List[QueryParam]()
    params_get_vanilla_utf8_query.append(QueryParam("ሴ", "bar"))
    var headers_get_vanilla_utf8_query = List[Header]()
    headers_get_vanilla_utf8_query.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_utf8_query.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("get-vanilla-utf8-query", "GET", "/", params_get_vanilla_utf8_query^, headers_get_vanilla_utf8_query^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n%E1%88%B4=bar\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\neb30c5bed55734080471a834cc727ae56beb50e5f39d1bff6d0d38cb192a7073", "2cdec8eed098649ff3a119c94853b13c643bcf08f8b0a1d91e12c9027818dd04"))

    var params_get_vanilla_with_session_token = List[QueryParam]()
    var headers_get_vanilla_with_session_token = List[Header]()
    headers_get_vanilla_with_session_token.append(Header("Host", "example.amazonaws.com"))
    headers_get_vanilla_with_session_token.append(Header("X-Amz-Date", "20150830T123600Z"))
    headers_get_vanilla_with_session_token.append(Header("X-Amz-Security-Token", "6e86291e8372ff2a2260956d9b8aae1d763fbf315fa00fa31553b73ebf194267"))
    out.append(SigV4Case("get-vanilla-with-session-token", "GET", "/", params_get_vanilla_with_session_token^, headers_get_vanilla_with_session_token^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "GET\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\nx-amz-security-token:6e86291e8372ff2a2260956d9b8aae1d763fbf315fa00fa31553b73ebf194267\n\nhost;x-amz-date;x-amz-security-token\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n067b36aa60031588cea4a4cde1f21215227a047690c72247f1d70b32fbbfad2b", "07ec1639c89043aa0e3e2de82b96708f198cceab042d4a97044c66dd9f74e7f8"))

    var params_post_header_key_case = List[QueryParam]()
    var headers_post_header_key_case = List[Header]()
    headers_post_header_key_case.append(Header("Host", "example.amazonaws.com"))
    headers_post_header_key_case.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-header-key-case", "POST", "/", params_post_header_key_case^, headers_post_header_key_case^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n553f88c9e4d10fc9e109e2aeb65f030801b70c2f6468faca261d401ae622fc87", "5da7c1a2acd57cee7505fc6676e4e544621c30862966e37dddb68e92efbe5d6b"))

    var params_post_header_key_sort = List[QueryParam]()
    var headers_post_header_key_sort = List[Header]()
    headers_post_header_key_sort.append(Header("Host", "example.amazonaws.com"))
    headers_post_header_key_sort.append(Header("My-Header1", "value1"))
    headers_post_header_key_sort.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-header-key-sort", "POST", "/", params_post_header_key_sort^, headers_post_header_key_sort^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nmy-header1:value1\nx-amz-date:20150830T123600Z\n\nhost;my-header1;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n9368318c2967cf6de74404b30c65a91e8f6253e0a8659d6d5319f1a812f87d65", "c5410059b04c1ee005303aed430f6e6645f61f4dc9e1461ec8f8916fdf18852c"))

    var params_post_header_value_case = List[QueryParam]()
    var headers_post_header_value_case = List[Header]()
    headers_post_header_value_case.append(Header("Host", "example.amazonaws.com"))
    headers_post_header_value_case.append(Header("My-Header1", "VALUE1"))
    headers_post_header_value_case.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-header-value-case", "POST", "/", params_post_header_value_case^, headers_post_header_value_case^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nmy-header1:VALUE1\nx-amz-date:20150830T123600Z\n\nhost;my-header1;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nd51ced243e649e3de6ef63afbbdcbca03131a21a7103a1583706a64618606a93", "cdbc9802e29d2942e5e10b5bccfdd67c5f22c7c4e8ae67b53629efa58b974b7d"))

    var params_post_sts_header_after = List[QueryParam]()
    var headers_post_sts_header_after = List[Header]()
    headers_post_sts_header_after.append(Header("Host", "example.amazonaws.com"))
    headers_post_sts_header_after.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-sts-header-after", "POST", "/", params_post_sts_header_after^, headers_post_sts_header_after^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n553f88c9e4d10fc9e109e2aeb65f030801b70c2f6468faca261d401ae622fc87", "5da7c1a2acd57cee7505fc6676e4e544621c30862966e37dddb68e92efbe5d6b"))

    var params_post_sts_header_before = List[QueryParam]()
    var headers_post_sts_header_before = List[Header]()
    headers_post_sts_header_before.append(Header("Host", "example.amazonaws.com"))
    headers_post_sts_header_before.append(Header("X-Amz-Date", "20150830T123600Z"))
    headers_post_sts_header_before.append(Header("X-Amz-Security-Token", "AQoDYXdzEPT//////////wEXAMPLEtc764bNrC9SAPBSM22wDOk4x4HIZ8j4FZTwdQWLWsKWHGBuFqwAeMicRXmxfpSPfIeoIYRqTflfKD8YUuwthAx7mSEI/qkPpKPi/kMcGdQrmGdeehM4IC1NtBmUpp2wUE8phUZampKsburEDy0KPkyQDYwT7WZ0wq5VSXDvp75YU9HFvlRd8Tx6q6fE8YQcHNVXAkiY9q6d+xo0rKwT38xVqr7ZD0u0iPPkUL64lIZbqBAz+scqKmlzm8FDrypNC9Yjc8fPOLn9FX9KSYvKTr4rvx3iSIlTJabIQwj2ICCR/oLxBA=="))
    out.append(SigV4Case("post-sts-header-before", "POST", "/", params_post_sts_header_before^, headers_post_sts_header_before^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\nx-amz-security-token:AQoDYXdzEPT//////////wEXAMPLEtc764bNrC9SAPBSM22wDOk4x4HIZ8j4FZTwdQWLWsKWHGBuFqwAeMicRXmxfpSPfIeoIYRqTflfKD8YUuwthAx7mSEI/qkPpKPi/kMcGdQrmGdeehM4IC1NtBmUpp2wUE8phUZampKsburEDy0KPkyQDYwT7WZ0wq5VSXDvp75YU9HFvlRd8Tx6q6fE8YQcHNVXAkiY9q6d+xo0rKwT38xVqr7ZD0u0iPPkUL64lIZbqBAz+scqKmlzm8FDrypNC9Yjc8fPOLn9FX9KSYvKTr4rvx3iSIlTJabIQwj2ICCR/oLxBA==\n\nhost;x-amz-date;x-amz-security-token\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nc237e1b440d4c63c32ca95b5b99481081cb7b13c7e40434868e71567c1a882f6", "85d96828115b5dc0cfc3bd16ad9e210dd772bbebba041836c64533a82be05ead"))

    var params_post_vanilla = List[QueryParam]()
    var headers_post_vanilla = List[Header]()
    headers_post_vanilla.append(Header("Host", "example.amazonaws.com"))
    headers_post_vanilla.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-vanilla", "POST", "/", params_post_vanilla^, headers_post_vanilla^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n553f88c9e4d10fc9e109e2aeb65f030801b70c2f6468faca261d401ae622fc87", "5da7c1a2acd57cee7505fc6676e4e544621c30862966e37dddb68e92efbe5d6b"))

    var params_post_vanilla_empty_query_value = List[QueryParam]()
    params_post_vanilla_empty_query_value.append(QueryParam("Param1", "value1"))
    var headers_post_vanilla_empty_query_value = List[Header]()
    headers_post_vanilla_empty_query_value.append(Header("Host", "example.amazonaws.com"))
    headers_post_vanilla_empty_query_value.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-vanilla-empty-query-value", "POST", "/", params_post_vanilla_empty_query_value^, headers_post_vanilla_empty_query_value^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\nParam1=value1\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n9d659678c1756bb3113e2ce898845a0a79dbbc57b740555917687f1b3340fbbd", "28038455d6de14eafc1f9222cf5aa6f1a96197d7deb8263271d420d138af7f11"))

    var params_post_vanilla_query = List[QueryParam]()
    params_post_vanilla_query.append(QueryParam("Param1", "value1"))
    var headers_post_vanilla_query = List[Header]()
    headers_post_vanilla_query.append(Header("Host", "example.amazonaws.com"))
    headers_post_vanilla_query.append(Header("X-Amz-Date", "20150830T123600Z"))
    out.append(SigV4Case("post-vanilla-query", "POST", "/", params_post_vanilla_query^, headers_post_vanilla_query^, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\nParam1=value1\nhost:example.amazonaws.com\nx-amz-date:20150830T123600Z\n\nhost;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\n9d659678c1756bb3113e2ce898845a0a79dbbc57b740555917687f1b3340fbbd", "28038455d6de14eafc1f9222cf5aa6f1a96197d7deb8263271d420d138af7f11"))

    var params_post_x_www_form_urlencoded = List[QueryParam]()
    var headers_post_x_www_form_urlencoded = List[Header]()
    headers_post_x_www_form_urlencoded.append(Header("Content-Type", "application/x-www-form-urlencoded"))
    headers_post_x_www_form_urlencoded.append(Header("Host", "example.amazonaws.com"))
    headers_post_x_www_form_urlencoded.append(Header("Content-Length", "13"))
    headers_post_x_www_form_urlencoded.append(Header("X-Amz-Date", "20150830T123600Z"))
    headers_post_x_www_form_urlencoded.append(Header("X-Amz-Content-Sha256", "9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e"))
    out.append(SigV4Case("post-x-www-form-urlencoded", "POST", "/", params_post_x_www_form_urlencoded^, headers_post_x_www_form_urlencoded^, "9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\ncontent-length:13\ncontent-type:application/x-www-form-urlencoded\nhost:example.amazonaws.com\nx-amz-content-sha256:9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e\nx-amz-date:20150830T123600Z\n\ncontent-length;content-type;host;x-amz-content-sha256;x-amz-date\n9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\nb1edd1d03544c25390e32085d55b57acc9a3961bb59415ff86c45c3d89d16cfb", "d3875051da38690788ef43de4db0d8f280229d82040bfac253562e56c3f20e0b"))

    var params_post_x_www_form_urlencoded_parameters = List[QueryParam]()
    var headers_post_x_www_form_urlencoded_parameters = List[Header]()
    headers_post_x_www_form_urlencoded_parameters.append(Header("Content-Type", "application/x-www-form-urlencoded; charset=utf-8"))
    headers_post_x_www_form_urlencoded_parameters.append(Header("Host", "example.amazonaws.com"))
    headers_post_x_www_form_urlencoded_parameters.append(Header("Content-Length", "13"))
    headers_post_x_www_form_urlencoded_parameters.append(Header("X-Amz-Date", "20150830T123600Z"))
    headers_post_x_www_form_urlencoded_parameters.append(Header("X-Amz-Content-Sha256", "9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e"))
    out.append(SigV4Case("post-x-www-form-urlencoded-parameters", "POST", "/", params_post_x_www_form_urlencoded_parameters^, headers_post_x_www_form_urlencoded_parameters^, "9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e", "AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "us-east-1", "service", "20150830T123600Z", True, "POST\n/\n\ncontent-length:13\ncontent-type:application/x-www-form-urlencoded; charset=utf-8\nhost:example.amazonaws.com\nx-amz-content-sha256:9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e\nx-amz-date:20150830T123600Z\n\ncontent-length;content-type;host;x-amz-content-sha256;x-amz-date\n9095672bbd1f56dfc5b65f3e153adc8731a4a654192329106275f4c7b24d0b6e", "AWS4-HMAC-SHA256\n20150830T123600Z\n20150830/us-east-1/service/aws4_request\na89f1a5b53e37702ee6363ce1da3ce8f54386f3c8f352ae652153c2982a0bc4d", "328d1b9eaadca9f5818ef05e8392801e091653bafec24fcab71e7344e7f51422"))
    return out^
