#!/usr/bin/env python3
"""Turn the AWS `aws-sig-v4-test-suite` into a Mojo fixture module.

The suite ships as one directory per case: `request.txt` (a raw HTTP/1.1
request), `context.json` (credentials, region, service, timestamp,
normalization and sign-body flags) and the expected
`header-canonical-request.txt` / `header-string-to-sign.txt` /
`header-signature.txt`. This script reconstructs the *inputs* a signer is
given — the signer is what adds `X-Amz-Date`, `X-Amz-Security-Token` and
`X-Amz-Content-Sha256` — and emits them next to the expected outputs.

Usage: python3 tools/gen_sigv4_vectors.py <path to .../aws-signing-test-suite/v4> > tests/sigv4_vectors.mojo
"""
import hashlib
import json
import os
import sys
from urllib.parse import unquote

# obs-fold header values (a value continued on the next line) were removed
# from HTTP/1.1 in RFC 7230 and cannot be expressed as a Name/Value pair.
SKIP = {"get-header-value-multiline"}


def mojo_str(s):
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return '"' + out + '"'


def parse_request(raw):
    head, _, body = raw.partition("\n\n")
    lines = head.split("\n")
    start = lines[0]
    method, rest = start.split(" ", 1)
    target = rest.rsplit(" ", 1)[0]
    path, _, query = target.partition("?")
    headers = []
    for line in lines[1:]:
        if not line.strip():
            continue
        name, _, value = line.partition(":")
        headers.append((name, value))
    params = []
    if query:
        for part in query.split("&"):
            if not part:
                continue
            k, _, v = part.partition("=")
            params.append((unquote(k), unquote(v)))
    return method, path, params, headers, body


def main():
    root = sys.argv[1]
    cases = []
    for name in sorted(os.listdir(root)):
        d = os.path.join(root, name)
        if not os.path.isdir(d) or name in SKIP:
            continue
        need = ["request.txt", "context.json", "header-canonical-request.txt",
                "header-string-to-sign.txt", "header-signature.txt"]
        if not all(os.path.exists(os.path.join(d, f)) for f in need):
            continue
        ctx = json.load(open(os.path.join(d, "context.json")))
        raw = open(os.path.join(d, "request.txt"), encoding="utf-8").read()
        method, path, params, headers, body = parse_request(raw)
        ts = ctx["timestamp"]  # 2015-08-30T12:36:00Z
        amz_date = ts.replace("-", "").replace(":", "")
        creds = ctx["credentials"]
        token = creds.get("token", "")
        payload_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()

        canonical = open(os.path.join(d, "header-canonical-request.txt"), encoding="utf-8").read()
        # Which of the signer-supplied headers were *signed* is a per-case
        # choice (post-sts-header-after attaches the session token only after
        # signing), so read it back off the expected canonical request rather
        # than guessing from the context flags.
        signed_names = canonical.split("\n")[-2].split(";")
        signed_headers = list(headers)
        signed_headers.append(("X-Amz-Date", amz_date))
        if token and "x-amz-security-token" in signed_names:
            signed_headers.append(("X-Amz-Security-Token", token))
        if ctx.get("sign_body") and "x-amz-content-sha256" in signed_names:
            signed_headers.append(("X-Amz-Content-Sha256", payload_hash))

        cases.append(dict(
            name=name, method=method, path=path, params=params,
            headers=signed_headers, payload_hash=payload_hash,
            access_key=creds["access_key_id"],
            secret_key=creds["secret_access_key"],
            region=ctx["region"], service=ctx["service"],
            amz_date=amz_date, normalize=bool(ctx.get("normalize")),
            canonical=canonical,
            sts=open(os.path.join(d, "header-string-to-sign.txt"), encoding="utf-8").read(),
            signature=open(os.path.join(d, "header-signature.txt"), encoding="utf-8").read().strip(),
        ))

    w = sys.stdout.write
    w('"""AWS SigV4 test vectors — GENERATED by tools/gen_sigv4_vectors.py.\n\n')
    w("Source: the published `aws-sig-v4-test-suite`, as vendored in\n")
    w("awslabs/aws-c-auth (`tests/aws-signing-test-suite/v4`). Each case gives the\n")
    w("signer's inputs and the expected canonical request, string to sign and\n")
    w("signature. `get-header-value-multiline` is omitted: obs-fold header values\n")
    w("were removed from HTTP/1.1 by RFC 7230 and cannot be expressed as a\n")
    w('Name/Value pair.\n"""\n\n')
    w("from objectstore.http import Header\n")
    w("from objectstore.sigv4 import QueryParam\n\n\n")
    w("@fieldwise_init\nstruct SigV4Case(Copyable, Movable):\n")
    for f, t in [("name", "String"), ("method", "String"), ("path", "String"),
                 ("params", "List[QueryParam]"), ("headers", "List[Header]"),
                 ("payload_hash", "String"), ("access_key", "String"),
                 ("secret_key", "String"), ("region", "String"),
                 ("service", "String"), ("amz_date", "String"),
                 ("normalize", "Bool"), ("canonical", "String"),
                 ("sts", "String"), ("signature", "String")]:
        w("    var %s: %s\n" % (f, t))
    w("\n\ndef sigv4_cases() -> List[SigV4Case]:\n")
    w("    var out = List[SigV4Case]()\n")
    for c in cases:
        w("\n    var params_%s = List[QueryParam]()\n" % c["name"].replace("-", "_"))
        pv = "params_" + c["name"].replace("-", "_")
        for k, v in c["params"]:
            w("    %s.append(QueryParam(%s, %s))\n" % (pv, mojo_str(k), mojo_str(v)))
        hv = "headers_" + c["name"].replace("-", "_")
        w("    var %s = List[Header]()\n" % hv)
        for k, v in c["headers"]:
            w("    %s.append(Header(%s, %s))\n" % (hv, mojo_str(k), mojo_str(v)))
        w("    out.append(SigV4Case(%s, %s, %s, %s^, %s^, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s))\n" % (
            mojo_str(c["name"]), mojo_str(c["method"]), mojo_str(c["path"]),
            pv, hv, mojo_str(c["payload_hash"]), mojo_str(c["access_key"]),
            mojo_str(c["secret_key"]), mojo_str(c["region"]), mojo_str(c["service"]),
            mojo_str(c["amz_date"]), "True" if c["normalize"] else "False",
            mojo_str(c["canonical"]), mojo_str(c["sts"]), mojo_str(c["signature"])))
    w("    return out^\n")


main()
